### ISSUE TITLE
必要機能洗い出し

### ISSUE THREAD

**Issue by RyotaAbe1014** [totot1010/Jisui#12]

**Comment by totot1010** [comment]
- 認証機能
  - サインアップ
    - メールアドレス
    - Googleログイン
  - ログイン
  - ログアウト
- 料理画像アップロード機能
  - 値段、料理名、コメントと一緒にアップロードできる
- 料理画像を閲覧できるタイムライン機能
- 他の人の投稿にいいね機能
- 他の人の投稿にコメント機能
- マイページ
  - 名前
  - メールアドレス
  - パスワードリセット
  - 家計簿を公開するかの設定
- 通知機能
- 家計簿を確認する機能
  - グラフで可視化
  - 他のユーザーの家計簿を見たい
- GitHubの草機能

**Comment by RyotaAbe1014** [comment]
昨日の洗い出しみたいなところはできたと思うので一旦クローズします！
