### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by totot1010** [totot1010/Jisui#21]

**Comment by totot1010** [comment]
エンティティ

- User(ユーザー)
  - user_id(主キー)
  - username(string)
  - email(email)
  - password 
  - created_at(datetime)
  - updated_at(datetime)
- Post(投稿)
  - post_id(主キー)
  - 投稿したユーザー(User)
  - 料理名(string)
  - 値段(int)
  - created_at(datetime)
  - updated_at(datetime)
- DishImage(料理画像)
  - dish_image_id(主キー)
  - post(Post: 投稿)
  - image_url(string)
  - created_at(datetime)
  - updated_at(datetime)
- Like(いいね)
  - like_id(主キー)
  - user(User: いいねしたユーザー)
  - post(Post: 投稿したユーザー)
  - created_at(datetime)
  - updated_at(datetime)

**Comment by RyotaAbe1014** [comment]
主キーは基本的に`id`でいいと思います`like_`みたいなのは不要かなと思います

**Comment by RyotaAbe1014** [comment]
一つの投稿に対して複数の画像が紐づきますか？

**Comment by RyotaAbe1014** [comment]
posts_likesとかの方が明示的でわかりやすいかも

**Comment by RyotaAbe1014** [comment]
image_urlということは外部ストレージにアップするイメージで良いですか_

**Comment by RyotaAbe1014** [comment]
ユーザーは物理削除？is_activeとかは不要？

**Comment by RyotaAbe1014** [comment]
他の人の投稿にコメント機能と使用には書いてあるのでコメントテーブルも必要だと思います！

**Comment by totot1010** [comment]
> 主キーは基本的にidでいいと思いますlike_みたいなのは不要かなと思います

了解です

> 一つの投稿に対して複数の画像が紐づきますか？

1つは寂しいので最大3つくらいつけたいですね

> posts_likesとかの方が明示的でわかりやすいかも

確かに！！

> image_urlということは外部ストレージにアップするイメージで良いですか_

そういうイメージでしたが、他の選択肢も要検討ですね

> ユーザーは物理削除？is_activeとかは不要？

削除は特になるてもいいかなと。必要であれば後からでも良いかなと

> 他の人の投稿にコメント機能と使用には書いてあるのでコメントテーブルも必要だと思います！

作っていきます

**Comment by totot1010** [comment]
> そういうイメージでしたが、他の選択肢も要検討ですね

他に選択肢ってバイナリにしてDBに保存するとかなんですかね？あんまりイメージがつかず。
サーバーのディスク？に保存するケースもあるんですかね

**Comment by RyotaAbe1014** [comment]
S3で良さそうですかね

**Comment by totot1010** [comment]
そうですね。無難にS3をイメージしてました

**Comment by RyotaAbe1014** [comment]
いいと思います！
